### ISSUE TITLE
[BUG] Cannot read pdf Attachment 

### ISSUE THREAD

**Issue by jaholm42** [TechbeeAT/jtxBoard#293] opened 2023-02-17 09:57 UTC
Taping on an attachment of a task displays a couple of apps, but no one of my  installed pdf reader is on the list (e.g. Xodo) 

**Device and version:**
 - Device: Samsung Galaxy S21
 - Android version Android 13
 - jtx Board version: 2.02.02-rc5
 - Downloaded from: Google Play

**Comment by patrickunterwegs** [comment] 2023-02-17 10:09
Hello @jaholm42 ,

I don't think that this is a problem of jtx Board, it seems more like an issue on your device or of the xodo app. 

I just tried it with xodo, the app just appears normally in the application picker when I open a pdf from jtx Board.

Do you have any special pdf? Can you upload it here?

**Comment by jaholm42** [comment] 2023-02-17 12:51
Hallo Patrik,

I don't agree, because  
I installed
- Adobe Acrobat
- All PDF
- FoxIT PDF Editor
- PDF Reader

Klicked on a PDF file in Total Commander and all these Apps are
presented as PDF viewer + Xodo + Samsung PDF Reader.

When clicking on the attachement of the Task in jtx nothing of these
where displayed!

Should I send your the Task File privately?

**Comment by patrickunterwegs** [comment] 2023-02-17 15:05
That's very strange. If you try another PDF, do you observe the same behavior?

Best would be if you could reproduce the problem with a PDF that contains no personal information and put it here publically. 
Otherwise it would be great if you could send it to patrick (at) techbee.at !

One more question: have you attached the PDF to an entry on a device and tried to open it or did you attach it, synchronize and then try to open it on another device?

**Comment by jaholm42** [comment] 2023-02-17 16:12
Ok, I found the source of the problem:

Creating an attachment with jtx results in an ICS containing: 
 
ATTACH;ENCODING=BASE64;VALUE=BINARY;FMTTYPE=application/pdf;X-LABEL=Aushang
 _Infoveranstaltungen.pdf:

Everything is good.

Creating an attachment with an othe programm e.g. gnome Evolution 
(Linux) results in an ICS containing:

ATTACH;VALUE=BINARY;FILENAME=Aushang_Infoveranstaltungen.pdf;
 ENCODING=BASE64:

This will be displayed in jtx with filename "jtx_7707120938354357238321.null"
(See Bug: "Attachment named get scrambled")
Therefore, no PDF app feels responsible for this attachment.

It's highly likely many other programs/apps will also break the rules
and didn't add  FMTTYPE=application/pdf.
I think it's a good idea to fix this in jtx when LABEL matches
*.PDF/*.pdf.

**Comment by patrickunterwegs** [comment] 2023-02-17 19:32
Thanks for the update! 
I think that also brings me to the right track on fixing this issue. As you mention this issue has probably the same root cause as #249. I'll check that soon in detail and provide a fix as soon!

**Comment by patrickunterwegs** [comment] 2023-02-18 09:03
Alright, so here's a quick explanation of what's going on: 
GNOME Evolution does not provide the FMTTYPE field, it provides only a parameter "FILENAME". But the parameter "FILENAME" is not defined in the standard, so actually the FMTTYPE is mandatory to determine the filetype and file extension. I have already considered the filename for KOrganiser where the parameter was named "X-LABEL". 

If jtx Board now should show the right filename, both parameters have to be checked downstream when adding them in jtx Board, but also the app needs to add both parameters again when synchronising upstream - so at the end both parameters need to be added with the same information (the filename).

It's not a good solution, but it's the only working solution to ensure compatibility with Evolution and KOrganiser...

As the fix is in the sync algorithm, I have opened: 
https://github.com/bitfireAT/ical4android/pull/83

This should then be added to DAVx5 v4.3.1!

Thanks again for your help 🙂

**Closed as completed by patrickunterwegs** 2023-02-18 09:03 UTC
Labels: bug
