### ISSUE TITLE
[BUG] Widget not updating by itself

### ISSUE THREAD

**Issue by Kiwzi** [TechbeeAT/jtxBoard#1134] opened 2024-01-06 16:49 UTC
Describe the bug
Widget wont update without opening the application first.

To Reproduce
Turn off "Sync on app start" on both devices to not have it interfere (we are using davx5 to do manual sync for testing).
Create a widget on device A showing for example all notes.
Create a note on device A, do a manual sync and confirm it is showing on the widget.
On device B go into the same note and edit it, then sync.
On device A open Davx5 and do a full sync.
Widget on device A not updated (for that to happen, even if the device is fully synced, you need to open the jtxBoard app)

Expected behavior
Entries should be updated on widgets after sync without having the need to open the jtxBoard application.

Device and version
Device: [Pixel 7a]
Android version: [Android 14, (GrapheneOS)]
jtx Board version: [Version: 2.06.05-beta09.gplay (206050023)]
Downloaded from: [Google Play]

**Comment by patrickunterwegs** [comment] 2024-01-10 21:20
Hi @Kiwzi , 
I'm a bit hesitant to make a change for this. 
Basically there's a (Google) Library for Widgets. jtx Board is uses the most modern one called Glance. I had a lot of troubles with it, but now it seems to work stable. 
Through this library the database is observed in the background, the widget itself would then refresh when changes are observed on the data. When exactly this refresh happens is controlled by the library (to be exact, a specific background worker in the widget library). Now there is a way to manually tell the widget that the data changed, but this doesn't mean that the widget would refresh immediately, as the system prevents too frequent updates within a short time.

Have you further observed this issue? Wouldn't the update of the widget happen anyway within 2-5 minutes after the sync?

**Comment by Kiwzi** [comment] 2024-01-10 22:09
Hmm, maybe I havent been patient enough, I will do some more testing to see if its good enough, thanks for your detailed response

**Comment by Kiwzi** [comment] 2024-01-11 21:58
Hi @patrickunterwegs ,
It has been about 4 hours since I edited a note on phone B, it did not update on my widget on phone A. So I opened and closed jtxBoard app and then the widget was updated. DavX is set to update every 15min on all types. I cant think of anything I am doing wrong while testing this. Want me to do longer timespan?

**Comment by patrickunterwegs** [comment] 2024-01-11 22:02
Thanks @Kiwzi for the update!
Then I will add a piece of code soon to notify the library to update the widget explicitly. I would like to release 2.7.0 soon, then I will add the change in a 2.7.1 beta (probably some time next week)

**Comment by patrickunterwegs** [comment] 2024-01-23 21:08
Hi @Kiwzi , sorry that this took a bit, I added some explicit update calls on the widget when entries are changed by DAVx5. Still, there's no full control over the refresh. I have just uploaded 2.7.1-beta03, it should be available soon (within the next 2 hours) on Google Play. I'd appreciate if you could also have a check and give some feedback!

**Comment by Kiwzi** [comment] 2024-01-24 06:24
Updated to 2.7.1-beta03, then with phone B changed a note, waited for 7 hours without any updates on phone A widget, then opened and closed jtxBoard app and widget got updated. As far as I can see widgets are not updating by themself

**Comment by q-wertz** [comment] 2024-01-26 12:35
I'm having the same issue.
In my experience the widget doesn't even get updated after a few days.

Don't know if this is a separate issue but when the due date is soon (which is no remote change) the widget also does not change/refresh and mark it with a red due date.

**Comment by patrickunterwegs** [comment] 2024-01-27 12:37
@q-wertz which Android do you use? Also Graphene OS work Android 14?

I'm a bit lost with that issue. The library (Glance widget by Google) took over those refresh mechanisms. This also means that they provide a single method to tell the Widget manually to refresh. When this actually happens is then again up to the library (actually the worker they use). 
But basically the Widget should even refresh regularly without such a manual trigger. 

Have you checked if jtx Board has restrictive battery optimization settings set? Can you turn them off for jtx Board and see if it works better?

**Comment by q-wertz** [comment] 2024-01-27 22:12
I'm on android 13.

I also first thought it's a problem of battery optimization, but the app is set to unrestricted...

**Comment by patrickunterwegs** [comment] 2024-01-29 11:24
Hi @q-wertz , hi @Kiwzi , 
I have changed a setting that seems to have an impact on certain Android versions. May I ask you to update to 2.7.1-beta06?
Sorry for the trial and error, but it's hard when I can't reproduce the issue.

**Comment by q-wertz** [comment] 2024-01-29 17:42
I enrolled in the beta tester program :+1: Waiting for the beta update

Just to be sure: In [releases](https://github.com/TechbeeAT/jtxBoard/releases) there is only a version `2.7.1-beta02`  `2.7.2-beta06` which both are "old". Which one should contain the fix?

**Comment by patrickunterwegs** [comment] 2024-01-29 17:45
Sorry for the typo @q-wertz , the latest one, 2.7.2-beta06

**Comment by Kiwzi** [comment] 2024-01-30 16:22
It seems to be updating by itself now, though it takes between 8 and 16-ish hours. Just started a second test now to confirm.
Will check back tomorrow

**Comment by q-wertz** [comment] 2024-01-30 16:34
I can confirm that a task that is overdue today got a red date without interaction. Also testing with finished tasks.

**Comment by q-wertz** [comment] 2024-01-30 16:35
@Kiwzi what is your sync rate in DAVx5?

**Comment by Kiwzi** [comment] 2024-01-30 16:36
15min

**Comment by q-wertz** [comment] 2024-01-30 16:41
I can confirm that my widget also got an update (I accidentally triggered the DAVx5 manually but shouldn't matter).

So the bug seems to be fixed for me.

**Comment by Kiwzi** [comment] 2024-01-30 17:48
Issue is not that the widget is not updating when you force it manually (either by opening davx or jtxBoard), issue is that widget never updates if you never open either davx or jtxBoard.
I.e. I have a calendar widget (using same davx account) that updates itself without me opening any apps within my 15min davx sync rate.

**Comment by q-wertz** [comment] 2024-01-30 20:25
Yes, for me the issue was the same but as I said I think it is fixed. I double checked without triggering DAVx5 and still the widget is refreshed without further interaction...
But I'm on 2.08.01-beta06 now

**Comment by patrickunterwegs** [comment] 2024-01-30 21:38
Thank you for your feedback!
I'm glad it works for you now, @q-wertz !
Just to make it clear, that the bug is a bit random: There is a setting that would make the "receiver", that would then trigger the update of the widget, available to other apps. This doesn't make much sense as the original app should always be allowed to update its own widget. But some Android OEMs seem to require that anyway.

One more thing: In 288aa9031150b40c4a628e38aae5f546b3b20663 I have made a change to try to solve this issue, I will revert this change now and publish a last beta-version. I don't expect a negative effect on the refresh of the widget, but the code could have a negative effect on battery usage as the widget might get refreshed unnecessarily on a sync multiple times.

I hope it will also work for you @Kiwzi

**Comment by q-wertz** [comment] 2024-02-01 08:02
I think with the new develop version `2.07.01-beta07.gplay` the issue reappeared, but need to double check this evening...

Or was not fixed before and I just had "luck" in the previous tests...

**Comment by Kiwzi** [comment] 2024-02-01 14:21
Can confirm same findings as @q-wertz . About 20 hours now without widget updates. (again, it will ofc update if I open jtxBoard app)

**Comment by patrickunterwegs** [comment] 2024-02-02 20:58
Thank @q-wertz , @Kiwzi , I will bring that piece of code back then. It's on the way with 2.07.01-rc02

**Comment by patrickunterwegs** [comment] 2024-02-05 17:29
Hi @q-wertz , @Kiwzi , did you make any different experiences with [v2.7.2-rc2](https://github.com/TechbeeAT/jtxBoard/releases/tag/v2.7.2-rc2) ?

**Comment by q-wertz** [comment] 2024-02-05 19:04
I can only update to `2.07.01-rc2`...

Will report back

**Comment by Kiwzi** [comment] 2024-02-05 22:11
I did some testing tonight (v2.7.2-rc2), it seems fixed :D
Will do some more testing tomorrow to check how quickly it updates, so far my guess is every 15min (as set in davx)

**Comment by q-wertz** [comment] 2024-02-06 14:30
On `2.07.01-rc2.gplay` which is the newest version in gplay developer it also seems to be fixed for me...

**Comment by Kiwzi** [comment] 2024-02-06 15:14
It has stopped updating.... Even restarted my phone. Today there has been zero widget updates for the past 8 hours.
Edit: Just checked again, it has now updated, dunno when, but it took some hours.

**Comment by Kiwzi** [comment] 2024-02-08 11:19
My last comment may have been innacurate due to my server had some issues.
New test today updated within 4 hours. Will commence second test  later today

**Comment by patrickunterwegs** [comment] 2024-02-08 16:03
Thanks for your checks @q-wertz and @Kiwzi . 
I will publish the current version now, at least the changes seem to have had a positive effect! 🙂

**Comment by Kiwzi** [comment] 2024-02-09 19:11
Still on v2.7.2-rc2, and can confirm it is updating the widget, but at random, first test was about 12 hour before widget bothered to update, second, third and fourth test it updated within 20-30 minutes, fifth test still running for about 4 hours.
Atleast it is updating :)
Will not commence further testing before @patrickunterwegs has asked for it.

**Comment by patrickunterwegs** [comment] 2024-02-16 21:42
Thank you for your update @Kiwzi ! :-)
Then I will close this issue for now. If you experience any more troubles, just let me know. I also hope that Google will provide an updated version of the library that gives a bit more flexibility and options for developers.

**Closed as completed** 2024-02-16 21:42 UTC
Labels: bug

**Comment by ikcalB** [comment] 2025-01-11 11:11
Hi @patrickunterwegs 

Unfortunately I seem to have the same issue: widget not updating.
For me otoh it does not even update after opening the jtx board app.

Do you want to continue here or open a new ticket?

Galaxy A55 5G - android 14
DAVx 5 and jtx up to date from playstore

Tnx for the awesome app!

**Comment by patrickunterwegs** [comment] 2025-01-14 16:13
Hi @ikcalB , may I ask you to observe the problem with the latest version as well? There was also a major upgrade of the widget library.
You could join the beta channel on Google Play and download 2.10.00-beta02.gplay. Otherwise please be a bit patient, I'll release this version soon.

**Comment by ikcalB** [comment] 2025-01-16 15:16
Hi @patrickunterwegs tnx for your fast reply.

Tried the beta since 2days ago, seems to work for the moment

**Comment by patrickunterwegs** [comment] 2025-01-21 15:02
@ikcalB , thank you for the feedback!

**Comment by ikcalB** [comment] 2025-01-21 17:34
Thanks for jtx ;)

Btw: marking (multiple) tasks as done is behaving sketchy again. Is this maybe related, or should i file a new bug:

In the widget, marking multiple tasks as done (checkmark): checkmark displays. Open jtx to make sure changes are applied: not all are/remain done. Going back to home screen, now previously checked tasks are unchecked
