### ISSUE TITLE
[BUG] 403 Forbidden error when syncing task with alert to GMX/web.de

### ISSUE THREAD

**Issue by duncan-blues** [TechbeeAT/jtxBoard#513] opened 2023-04-26 16:10 UTC
When creating a new task and adding an alert to it (either specific date or e.g. "when due"), the caldav server refuses the sync with a 403 Forbidden error.
Creating a similar task e.g. with Gnome Evolution works. Task looks just the same in jtx board and can also be edited successfully (e.g. changing the date on the existing alert). Only adding a new alert again causes a 403 Forbidden error.

**Comment by duncan-blues** [comment] 2023-04-26 16:22
[davx5-debug.zip](https://github.com/TechbeeAT/jtxBoard/files/11335150/davx5-debug.zip)

**Comment by patrickunterwegs** [comment] 2023-04-26 17:27
Hey @duncan-blues !
Thanks for the logs, the problem is the following:

`Invalid calendar object: Property [DESCRIPTION] must be specified once`

It's a but strange that it only happens with synchronized entries... But anyway, I'll review the code tonight 👍

**Comment by patrickunterwegs** [comment] 2023-04-26 19:34
Alright, so here's what happened: 

The standard seems to require a description: 
![grafik](https://user-images.githubusercontent.com/72232737/234682966-438a7e98-7c9e-47d5-a23b-cac530f38897.png)

But in jtx Board I'm just using the summary and description for the notification. I think it's a bit useless to define a separate text for the notification. So the description field for alarms is basically there, but it's always NULL. 
The solution is now to set it to empty, this makes also the "DESCRIPTION:" property appear in the sync and web.de/gmx will accept it. 
By the way it seems like it only appears there on web.de/gmx. But I also have to say that they are basically right about their interpretation of the standard and that it needs to be fixed in jtx Board.

**Closed as completed** 2023-04-26 19:38 UTC

**Comment by patrickunterwegs** [comment] 2023-04-26 20:55
@duncan-blues the new version beta10 is out now, could you also check on your side if the problem is solved? Please note that you should remove the alarm and add it again to resolve the issue!
