### ISSUE TITLE
[BUG] the app freeze when adding or editing tasks

### ISSUE THREAD

**Issue by 87113** [TechbeeAT/jtxBoard#867] opened 2023-09-14 18:38 UTC
First of all, thank you for this great app :) 

**Describe the bug**
The app randomly freeze when I edit or add a task. 

**To Reproduce**
1. Go to task 
3. Click on add a task
4. Try to add a date or type some text
5. The app's animations are not smooth then 
6. The app freeze sometimes, usually when I open it for the first time since a long time. 

**Expected behavior**
The app should not freeze. 

Sometimes I wait and I'm able to continue, sometimes the app crash and I lose my new task

**Screenshots**

![Screenshot_20230914-202453_jtx Board](https://github.com/TechbeeAT/jtxBoard/assets/102969362/bb99434a-b95e-4628-9ce8-9a6d7597dbb5)

**Device and version:**
I synchronize all my tasks with a nextcloud through DAVx5.
 - Device: FairPhone3
 - Android version: /e/os v1.14 -> Android 12
 - jtx Board version: 2.05.04.ose
 - Downloaded from: f-droid

**Comment by patrickunterwegs** [comment] 2023-09-17 07:51
Hi @87113 !
Are you working there with recurring tasks and a lot of instances?
Lately such issues weren't reported and there was no major change in this area.
Could you please also try to turn autosave off to check if it makes a difference? It is possible that autosave already triggers the sync in the background which then slows down the app...

**Comment by graue70** [comment] 2023-09-23 11:19
I also continue experience UI hangs regularly when editing tasks after clicking on task notifications. I mentioned the number of tasks and recurring tasks in https://github.com/TechbeeAT/jtxBoard/issues/685.

Since I don't know the cause of the symptom I don't know whether https://github.com/TechbeeAT/jtxBoard/issues/884 is more appropriate in my case.

**Comment by patrickunterwegs** [comment] 2023-09-29 20:59
Hi @graue70 , I think I'm your case it's different. Could you please deactivate the setting to sync on app start in the settings of jtx Board and observe if you still encounter the same issue?

**Comment by graue70** [comment] 2023-09-30 01:35
That seems to have made the problem go away (again). Shouldn't the sync happen on a background task without affecting the UI?

**Comment by patrickunterwegs** [comment] 2023-09-30 07:51
Thanks for checking!
So it's clear that there is a connection with the sync. 
Technically yes, the sync runs on a background thread and should not affect the UI. 
The problem is now related to the UI-Framework (Jetpack Compose): The app observes changes in the database and refreshes the UI every time a relevant attribute changes. It seems like in some cases it happens that so many refreshes of the UI are triggered, that it blocks the UI... 
I will review the code and see what I can do there.

**Comment by graue70** [comment] 2023-10-13 18:38
I stand corrected: I still experience sluggishness, hangs and crashes even though the 'sync at Start' setting is disabled.

**Comment by 87113** [comment] 2023-11-03 15:22
> Hi @87113 ! Are you working there with recurring tasks and a lot of instances? Lately such issues weren't reported and there was no major change in this area. Could you please also try to turn autosave off to check if it makes a difference? It is possible that autosave already triggers the sync in the background which then slows down the app...

Hi, I don't find the autosave but I deactivate the "sync on app start" and "sync on pull down" and I get the same freeze.
Maybe less often. 

Now I use the version: 2.06.01.ose (206010008)

**Comment by patrickunterwegs** [comment] 2023-12-03 13:48
Hi @graue70 , hi @87113 , did you maybe have the chance to check if 2.6.3 brought some improvements in this area? I have changed some parts of the code that should prevent or at least reduce such blocking behavior.

**Comment by patrickunterwegs** [comment] 2023-12-03 13:57
I will close this issue for now, if you still encounter similar issues, please let me know.

**Closed as completed by patrickunterwegs** 2023-12-03 13:57 UTC
Labels: bug

**Comment by rogercreagh** [comment] 2023-12-04 08:03
No sooner done than it happened again. As I said in one of the other two threads on this (#884 and #758 ) a couple of days ago I switched sync back on on both DavX5 (every 60 minutes and on changes) and JtxB (sync on startup). 

Yesterday I noticed the UI slowing down and freezing while making a short entry more or less straight after opening the app - which makes me think it is a conflict between Davx being told there is a change and doing a sync while JtxB is doing its startup sync.

Then today while making a longer entry right after startup it was also slowing down. I stopped typing for a bit and it cleared but a few minutes later it was doing it again. This time it was just I was finishing typing. I switched to set the status and it froze completely, then stuttered (the editor pane closed and the status change appeared to be set so I started to type a category and it crashed right out - app closed.

I turned off sync in Davx5, reopened jtxb and the text was all there but neither status change or categories had taken.

Tomorrow I will leave Davx5 sync off and leave jtxb to sync on start and see what happens.

This thread, #884 and #758 all seem to be the same so I suggest only reopening one of them and linking the others.

Edit - jtx version is 2.6.3, davx5 version is 4.3.11

**Comment by graue70** [comment] 2023-12-06 21:38
> Hi @graue70 , hi @87113 , did you maybe have the chance to check if 2.6.3 brought some improvements in this area? I have changed some parts of the code that should prevent or at least reduce such blocking behavior.

I can't remember running into this issue again after my previous message. :+1:
