### ISSUE TITLE
[BUG] Widget crashes when group by status or classification is selected

### ISSUE THREAD

**Issue by tiptruck** [TechbeeAT/jtxBoard#471] opened 2023-04-16 12:37 UTC
**Describe the bug**
See attached screenshot

**To Reproduce**
1. Add a widget
2. Select group by 
3. Select either status or classification
4. select the tick to save
5. Error in screenshot occurs
![SmartSelect_20230416_193202_One UI Home](https://user-images.githubusercontent.com/53040514/232311468-3af9ccd2-2cb2-435c-8f2f-9dee593507db.jpg)

**Device and version:**
 - Device: [e.g. Samsung Galaxy S22] Samsung Tab S7
 - Android version [e.g. Android 11] 13
 - jtx Board version: [e.g. 2.1.0] 2.03.01-rc04.ose (203010004)
 - Downloaded from: [e.g. Google Play, f-Droid, ...] F-droid

**Comment by patrickunterwegs** [comment] 2023-04-16 13:15
Thanks a lot, I just reproduced it, I'll fix it soon!

**Comment by patrickunterwegs** [comment] 2023-04-16 16:22
Thanks again @tiptruck , I found the root cause and fixed it, it will be part of the next version!

**Closed as completed** 2023-04-16 16:27 UTC
Labels: bug
