### ISSUE TITLE
[BUG] widget multiplies entries + display issue

### ISSUE THREAD

**Issue by burningT** [TechbeeAT/jtxBoard#1355] opened 2024-04-22 06:34 UTC
**Describe the bug**
Tasks are shown repeatedly at the end of the list in the widget. Other tasks are hidden and an arrow symbol is shown above these tasks. This seems to occur if the device is running for some days without reboot. Up to now I found no reliable way for reproduction, other than waiting.

**To Reproduce**
- Add some tasks to widget
- wait(?)

**Expected behavior**
A clear list without reproductions and without arrows.

**Screenshots**

![ResizedImage_2024-04-22_08-22-05_1824](https://github.com/TechbeeAT/jtxBoard/assets/5808054/b43945d3-fb94-4111-9976-5f035d0e50bd)

**Device and version**
 - SHIFT6mq
- Android version: 10
- jtx Board version: 2.07.04.gplay
- Downloaded from: Google Play

**Comment by patrickunterwegs** [comment] 2024-04-22 18:45
Hey @burningT !
Thanks for the issue report!
Did this problem just start happening in the latest version or already before?
And does it solve itself (e.g. when you open the app and close it)?

**Comment by burningT** [comment] 2024-04-24 19:51
Hi,
This one is a bit hiddeous. I am sure it occurred with the version before already. However, I am not sure if it occurred even earlier.

And indeed, right now it seems gone for no reason.

**Comment by patrickunterwegs** [comment] 2024-04-24 20:08
Hey @burningT , and to get it right, it still occurs regularly?
Can you tell me how many entries round about you have in the widget?

**Comment by burningT** [comment] 2024-04-24 20:21
Hi,
There are 13 entries in my widget right now. 
I will have an eye on it. I didnt recognize any pattern of occurrences up to now.

**Comment by burningT** [comment] 2024-04-30 19:42
The arrow is back today (possibly even earlier). There are 10 tasks and 4 subtasks in the widget now. Version is now 2.07.05.gplay. However, I still recognise no pattern.

**Comment by patrickunterwegs** [comment] 2024-04-30 20:05
Thanks for the update @burningT !
When you click on the line with the arrow, can you open it? If yes, could you export the entry and put it here as an ics? (Only if it doesn't contain any personal info)

**Comment by burningT** [comment] 2024-05-01 20:59
Yes indeed, I can open that line. However, it opens not the task displayed but another one. Funny wise it is a badly drafted task concerning jtx. Tidying it up ironically fixed the issue. Here is the original version: 
[ics_file.ics.txt](https://github.com/TechbeeAT/jtxBoard/files/15181319/ics_file.ics.txt)

**Comment by patrickunterwegs** [comment] 2024-05-02 15:34
Hey @burningT !
Thanks, I have tried it with that file, regrettably I couldn't reproduce the problem. 
However, I have made two small changes in the layout now. I hope this will have a positive impact and solve that problem as well.
The change will be available from 2.7.2-beta02, please let me know if this problem also occurs in this newer version! Thank you!

**Closed as completed** 2024-05-02 15:37 UTC
Labels: bug
