### ISSUE TITLE
[Feature] seperate widget for tasks.

### ISSUE THREAD

**Issue by zoroya1** [TechbeeAT/jtxBoard#424] opened 2023-04-04 14:58 UTC
**Is your feature request related to a problem? Please describe.**

>currently Jtx board does have nice widget but a task widget specially for task will be nice. 

**Describe the solution you'd like**

>In task widget user can tick main task or subtasks as done from widget, which saves time in opening app amd manually ticking done.

**Describe alternatives you've considered**

> other apps doesn't have nice task widget and jtx board can have it with Material you 💟

**Additional context**

**Comment by patrickunterwegs** [comment] 2023-04-04 15:02
Hey, which version of Android and jtx Board are you using?

**Comment by patrickunterwegs** [comment] 2023-04-04 15:09
Basically the app offers a fully configurable widget, but it's deactivated for Android versions below 9 (see #197). The problem is that thx Board uses the new, experimental way for widgets (Glance), but the latest version has a bug in older android versions and Google hasn't provided an update/fix for almost half a year... I hope they will provide a new version soon!

**Comment by patrickunterwegs** [comment] 2023-04-04 15:11
If this is not the problem, you can just choose tasks in the widget config, this would actually just create a view as you describe!

**Comment by zoroya1** [comment] 2023-04-04 16:46
> If this is not the problem, you can just choose tasks in the widget config, this would actually just create a view as you describe!

Awesome !
I am using latest version 2.03.00 rc from github using Obtainium on my aosp android 12.

Just wanted to have a task widget. But as you said, it has task widget intergrated in main widget then it's nice feature. Will try it 😃

**Comment by patrickunterwegs** [comment] 2023-04-04 19:57
Alright, so I will close this issue here, feel free to comment again if you still have any issues with it 😉

**Closed as completed** 2023-04-04 19:58 UTC
Labels: enhancement
