### ISSUE TITLE
[Feature] Changing default view (or maybe rearranging categories)

### ISSUE THREAD

**Issue by pacjo** [TechbeeAT/jtxBoard#747] opened 2023-08-05 15:05 UTC
**Is your feature request related to a problem? Please describe.**
Not exactly a problem, but I'd like an option to select Tasks or Notes as a default view, so that when I open the app, I don't have to switch from Journals, which I don't plan on using that much.

**Describe the solution you'd like**
In settings, there should be an option to select default view (or an option to rearrange views). Then upon opening the app, it should either display the selected view or show the first view (which would be different in case the order could be changed).

**Describe alternatives you've considered**
Manually switching the view. *Not great, not terrible.*

**Additional context**
I love your app. I've tried different apps over the years (most recently [OpenToday](https://github.com/FazziCLAY/OpenToday/)), but none had all the functionality I wanted. I was getting to the point of writing my own (today I searched for synchronization options), but then I found yours. It looks like it's exactly what I want, and I think it's better than whatever I could make.

**Comment by patrickunterwegs** [comment] 2023-08-05 15:29
Hey @pacjo !
Thank you for the feedback =)

Basically the app should open the last used tab. I think that should basically also cover your demand, right?
Does this work for you? I'm also asking because a similar logic had an issue lately and didn't save the last used top app bar mode correctly (but this one is fixed now)

**Comment by pacjo** [comment] 2023-08-05 15:58
> Basically the app should open the last used tab. I think that should basically also cover your demand, right? 

Yes it does. I noticed it just after opening the issue.

I would still prefer to have the option, but current behaviour is good enough. I will see, maybe I can add it myself.

**Comment by patrickunterwegs** [comment] 2023-08-05 17:32
If you're interested in making a small contribution, I can point you to some places 😉 
Basically I can imagine a new setting with "Settings for the item list" that says something like "Default tab..." with the options 'Last used tab' and then journals, notes, tasks. There is already a setting where the last used module is stored, so this can just be used as a setting in the settings menu.
So if you're interested, please let me know, otherwise I can just do it myself 😉

**Comment by pacjo** [comment] 2023-08-05 19:07
Let's leave this issue open for now. I will check and write back in at most a couple of days.

**Comment by patrickunterwegs** [comment] 2023-08-06 11:43
Hey @pacjo , 
I thought about this again, I'm not sure if it's a good idea. 
Basically when you have an app open, then you move it to the background and then to the foreground again, you usually expect to end up on the same screen again (at least the same main screen). 

As long as the app is in the memory, it makes sense to keep this behavior. 

When a setting is added to choose the start tab, I assume you would expect the app to open on the selected tab, but when you change it, switch to another app and then back, you'd still expect to end on the pectoralis selected tab and not on the tag you chose in the settings.
 
But the user is not aware when am app is killed by the system, even when choosing the app from the recent apps it could be completely recreated. 
I think the behavior then would be pretty random for the user, once it would open the last used tab, once the selected one from the settings... 

So I think it's better to not do this at all. What do you think? Or do you have another approach?

**Comment by pacjo** [comment] 2023-08-07 10:09
I agree with you. I opened this issue almost immediately after finding your app, so before any actual usage. After few days I got used to the current behaviour.

By the way, is there an option for manually arranging the list of notes and tasks?

**Comment by patrickunterwegs** [comment] 2023-08-07 11:14
Alright, so let's close this one.

About manual sort order: I have considered this many times. The database already has the necessary fields, but the UI functionality is missing... The problem is that there is no proper drag & drop solution to reorder a list in Jetpack Compose. (This was for example also requested in #150 ) There is a library, that could offer such a functionality, but it's outdated and the creator hasn't reacted on any pull requests for many months... I am hesitating to try some custom solution on my own. Eventually I keep postponing this topic all the time hoping that Google will provide a standard functionality in Jetpack Compose...

**Closed as completed by patrickunterwegs** 2023-08-07 11:14 UTC
Labels: enhancement
