### ISSUE TITLE
[BUG] Alarm notification doesn't work with recurring tasks

### ISSUE THREAD

**Issue by Thom1b** [TechbeeAT/jtxBoard#1007] opened 2023-11-08 07:33 UTC
Hi,

I always set alarm notification when a task starts, it works fine with single tasks. If I create a recurring task with alarm notification, the alarm won't work, there is no notification at all.
I didn't find anything in settings so I think this is a bug. Sorry if it's not.

Thanks.

 - Device: Xiaomi redmi note 5
 - Android version: Android 11 (LineageOS)
 - jtx Board version: 2.06.01.ose
 - Downloaded from: f-droid

**Comment by patrickunterwegs** [comment] 2023-11-08 19:40
Hi @Thom1b , could you send me a screenshot of how the alarm is defined on a recurring instance? I mean just the part where I can see the date and time.

**Comment by Thom1b** [comment] 2023-11-09 06:50
Of course :)
![Screenshot_20231109-074630_jtx_Board](https://github.com/TechbeeAT/jtxBoard/assets/22797303/4030365e-68ad-4e0a-b1d2-050abdfbe248)

**Comment by Thom1b** [comment] 2023-11-12 08:09
Hi,
Maybe you are a wizard or something and you did a magic trick to my phone: I didn't change anything, didn't update anything since my bug report and now notification works with recurring tasks, even in "Ne pas déranger" ("don't disturb") mode.
So I think we can close this bug report. Thanks for your time. Sorry for the noise.
Have a nice day!

**Comment by patrickunterwegs** [comment] 2023-11-12 08:17
Hey @Thom1b !
Thank you for the update! 
Indeed I tried it over the last days and it just worked for me. 

I will have a look once more at the code if a race condition could happen there: when things are done on one or more background processes, it can happen that one process is finished earlier than the other. So I would still like to review if it could happen that the alarms are scheduled before all instances are created in the background. (The problem is that it can be random which process finished first).

If the review doesn't show anything suspicious, then let's close the ticket. 😉
But anyhow, should it happen again, hat let me know!

**Comment by patrickunterwegs** [comment] 2023-12-03 13:59
I have reviewed the code and couldn't find anything suspicious, so I'm closing this ticket now. @Thom1b just let me know if anything like this happens again and I'll have a look once more.

**Closed as completed by patrickunterwegs** 2023-12-03 13:59 UTC
Labels: bug, wontfix
