### ISSUE TITLE
[BUG] [CRASH REPORT]

### ISSUE THREAD

**Issue by rogercreagh** [TechbeeAT/jtxBoard#758] opened 2023-08-08 08:24 UTC
**Describe the bug**
Editing a longish entry. Had it open for about 35 mins transcribing in data from another device. A fair amount of jumping back and insert/delete editing going on.
Suddenly, with no tap, the screen goes blank and then pops up `Sorry, this entry was either deleted in the background or could not be loaded. [Back]`
Press the [Back] button after a few moments contemplating the unfairness of the universe,screen clears again and the same message recurs,but this time the [Back] button doesn't do anything.
App appears to have locked up
System still working
Sync on another device and the entry is truncated mid sentence half way through the second paragraph. Everything thereafter is not there. The entry had been first created and sync'd the previous day with just the title and first sentence of summary, so some of this session  has been saved and sync'd and the rest lost

Force close on jtxB (the only option as screen is locked) and reload to find same result as on other device. 
AAARGH - that was a lot of complicated work to reproduce on a tablet touch keyboard :-( !!!

DavX5 is set for Calendars to sync every 30mins and immediately on local changes
The Davx5 Calendar properties say Last Sync'd Calendar Storage 08:48, jtxBoard 09:02 - which is about 20 mins after the crash - the crash happened about 08:30 so possibly 30 mins before 09:02. 

Nothing else is accessing the calendar - the only other device connected says last sync'd jtxBoard at 07:42 which is when I did opne and then close jtxB on it. jtxB not appearing in the open apps list on tht device. 

**To Reproduce**
I wish I knew - nothing unusual happened.Only other app possibly running in background would beDavx5

**Expected behavior**
This should not happen !!!!

**Screenshots**
n/a

**Device and version:**
 - Device:Boox NovaAir tablet
 - Android version  Android 11
 - jtx Board version: 2.5.1ose
 - Downloaded from: f-Droid

**Comment by rogercreagh** [comment] 2023-08-08 09:26
Just a thought - I wonder if this happens if you happen to be editing an item while it is being sync'd. Perhaps especially if you are not simply appending text but inserting or deleting further up the article?

There used to be a slight indication when a sync was taking place - an animated line towards the top of the screen - but I haven't seen it recently. Has it been deceased?  How about having a pop-up warning box when a sync starts which diasppears when it completes telling the user it might be a good idea to pause editing during the sync to avoid conflicts. The user could dismiss the box and continue at their own risk.

**Comment by patrickunterwegs** [comment] 2023-08-08 15:19
Hey @rogercreagh ,
Sorry for that bad behavior... :(
In this case it would have been helpful to have the crash report by Google, but for the OSE version nothing is forwarded.

So I can only review the code and try to reproduce the problem...

**Comment by rogercreagh** [comment] 2023-08-08 16:42
My suspicion, since this is probably the longest entry yet and I was editing text throughout it, is that it might be an interaction between the editor buffer flushing and the sync occurring. I don't know the exact time of the crash but it must have been pretty close to the 30 minute DavX5 sync interval. 

There was no markdown or funny stuff in the text.

The on-screen keyboard in use was OpenBoard

DavX5 is v4.3.5.1-ose

Any other info you need? I hope you do find a situation to recreate it.

**Comment by rogercreagh** [comment] 2023-08-10 07:04
@patrickunterwegs it just happened again. Same as last time, was editing a previous entry.
This time pressing back on the error pahe did take me back to the list but with about the last 50 entries missing. They gradually returned (as the sync progressed?)
There was a sync in progress. The DavX5 properties for the calendar said last synced Calendar Storage yesterday and jtxBoard 1 minute ago 07:46 (it was about a minute since it happened)
This was less than half an hour since I turned on the device.
Approx 5 minutes later the properties said Calendar Storage 07:52, jtxBoard 07:52 which to me imples that was a DavX5 initiated sync 30mins after I switched on and the crash was on a jtxB initiated sync?

**Comment by patrickunterwegs** [comment] 2023-08-13 16:20
Thanks @rogercreagh for the updates. I'll have a close look soon. 
One more detail: Do you usually have autosave on or off?

**Comment by patrickunterwegs** [comment] 2023-08-14 07:24
Hi @rogercreagh, 
I have reviewed the code and I found a place where possibily a race condition could cause a problem. I made the change and I will test it now.

**Comment by rogercreagh** [comment] 2023-08-14 09:10
It just did it again on v2.05.02, although this time pressing the back button after a wait for long enough for any background sync to finish (about 30secs is what sync currently takes) it did recover most of the text.

Sync on app start = on
sync on pull down = off
Autosave = on
Davx5 calendars sync = 30mins + immediately on local changes.

**Comment by patrickunterwegs** [comment] 2023-08-25 19:00
Hi @rogercreagh , did you observe this problem again since you updated to 2.5.3?

**Comment by rogercreagh** [comment] 2023-08-26 17:53
Not yet, but I only got 2.05.03 day before yesterday.
I have tried to install the beta apk direct from here but I am now getting an error message when doing that `App not installed as package conflicts with an existing package`. Previously (many versions ago) I was able to overinstall the apk onto the frdroid version and vice versa, but it seems no longer - so I am stuck with waiting for fdroid to catch up with new releases and can't install betas... :-(

**Comment by patrickunterwegs** [comment] 2023-08-26 17:56
Alright, no worries! 
Yes, you cannot upgrade from an f-Droid version to the developer signed version as f-Droid has it's own signing key (and you can only update with packages that have been signed with the same key)

**Comment by patrickunterwegs** [comment] 2023-09-16 14:16
Hi @rogercreagh , did this crash happen again?

**Comment by patrickunterwegs** [comment] 2023-11-28 20:34
Hello @rogercreagh , what's your experience with the latest version regarding this issue?

**Comment by rogercreagh** [comment] 2023-11-29 11:37
I've not seen it since 2.5.3 but I have turned off automatic sync in both Davx5 and jtxB and now only sync manually. Not ideal but at least I don't loose anything. I think the problem is really for Davx5 as there is no way to not have that sync when it detects a local change. That needs to be an option on their settings - timed sync without autosync on changes. I'm pretty sure that is what caused the problem.
I will try leaving Davx5 timed sync off and set jtxB to only sync on startup and when manually requested and see what happens.

Incidentally on my e-ink screen the rolling bar near the top that indicates sync in progress is not visible, so it is impossible to know whether a sync is happening or not.

**Comment by patrickunterwegs** [comment] 2023-12-03 13:51
Thanks @rogercreagh , I'll close this issue for now, please let me know if it happens again.

**Closed as completed by patrickunterwegs** 2023-12-03 13:51 UTC
Labels: bug

**Comment by rogercreagh** [comment] 2023-12-04 08:07
see new comment in #867 and #884
