### ISSUE TITLE
[BUG] Sort of tasks broken

### ISSUE THREAD

**Issue by q-wertz** [TechbeeAT/jtxBoard#814] opened 2023-08-22 09:59 UTC
**Describe the bug**
Since I think a week or two the sorting in the Widget seems to be broken.
In my case I have two Accounts and a Widget that shows all the tasks sorted by Due date and then by priority.

The first entries are correct but then after some scrolling additional entries appear that have an overdue due date. I didn't find out what's the cause.

The ones that appear after some scrolling are e.g. due on `10.02.2023 10:00` (Account A) and `22.08.2023` (Account B) (so no date vs datetime problem).
In between there are some tasks without a due date and/or beginning date at all. The latest due date from the correctly sorted begging of the tasks is `31.12.2024`.

I also had the feeling (couldn't reproduce it) that after playing with some settings (switching forth and back the `Sort by` possibilities) the order changed…

Might be related to fix of https://github.com/TechbeeAT/jtxBoard/issues/667?

**To Reproduce**
1. Go to Widget
2. Scroll down in the tasks
4. See some tasks that are not in the correct order

**Expected behavior**
The tasks are sorted by the due date in correct order

**Screenshots**
Start:
<img src="https://github.com/TechbeeAT/jtxBoard/assets/20948931/a66177e5-9b4c-49f5-8e21-1963abf11cee" alt="Correct beginning" width="50%">

Scrolled down (wrong?)
<img src="https://github.com/TechbeeAT/jtxBoard/assets/20948931/32f1379e-2657-40d3-b496-36419157aa9b" alt="Wrong?" width="50%">

**Device and version:**
 - Device: Nokia X20
 - Android version: Android 13
 - jtx Board version: 2.05.03.gplay (205030010)
 - Downloaded from: Google Play

**Comment by patrickunterwegs** [comment] 2023-08-22 17:45
Thanks @q-wertz !
I'll investigate and try to reproduce!

**Comment by patrickunterwegs** [comment] 2023-08-22 17:56
Hi @q-wertz , could you please check a detail: Do those entries have a "Completed" date set but are not checked (resp. have a progress of < 100)?

**Comment by q-wertz** [comment] 2023-08-22 18:45
Some of them have a Progress but none have the completed field set...

**Comment by q-wertz** [comment] 2023-08-22 18:46
I think I found one common thing:
the wrong ones have at least one tag

**Comment by q-wertz** [comment] 2023-08-22 19:20
Made a diff between a working one (left) and a wrong sorted one (right)
![grafik](https://github.com/TechbeeAT/jtxBoard/assets/20948931/42ac93f9-8dbc-432f-a29b-fbac359b5386)

**Comment by q-wertz** [comment] 2023-08-22 20:31
I digged a bit deeper. 

Checked if any field is available/not available in all cases.

Field | In working and not working tasks 
----- | :-----:
`PERCENT-COMPLETE=0` | :heavy_check_mark: 
`SEQUENCE` | :heavy_check_mark: 
`STATUS` | :heavy_check_mark: 

Until now didn't find any clue.

Just to make sure my configs, maybe I'm overseeing something:

<img src="https://github.com/TechbeeAT/jtxBoard/assets/20948931/7efa2568-88c7-4419-8d0d-ec1321760212" alt="1" width="50%">

<img src="https://github.com/TechbeeAT/jtxBoard/assets/20948931/da262213-9109-4956-bc73-a4c6f4084165" alt="2" width="50%">

**Comment by patrickunterwegs** [comment] 2023-08-23 19:37
Hey @q-wertz , thank you for your efforts to narrow the problem down!
I have checked yesterday, I couldn't reproduce the problem... maybe I'll have to check with more entries after all...
But when you apply the same filter settings in the app itself, do you also observe this weird behaviour?

**Comment by q-wertz** [comment] 2023-08-24 07:48
Thanks for checking.
In the app itself the same issue occurs (in list & grid view).

I also tried now sorting for start date, which is also not in correct order...

What really feels a little bit off is, that there seem to be two blocks of sorted items. To Block 1 is sorted in itself correctly and then follows Block 2 which then is also sorted in itself correctly.
For both accounts Block 2 does not contain any Tasks without any due date (but don't know if this is an coincidence) (checked them separately).

**Comment by q-wertz** [comment] 2023-08-24 07:55
For one of the accounts I read out all fields and gathered them. Maybe this is helpful...

Just altered the `SUMMARY` and `X-ALT-DESC;FMTTYPE=text/html` to not include personal information.

So it is just a set of all entries that appear. So e.g. in `PERCENT-COMPLETE` `not_working: {'50', '0'}` doesn't mean that all "wrong" entries have `50` there... 
As far as I can see there is no single exclusive entry that explains the behavior...

And I didn't check entry combinations.

```
CALSCALE
 working: ['GREGORIAN']
 not_working: ['GREGORIAN']
-----------------
PRODID
 working: ['-//Ximian//NONSGML Evolution Calendar//EN']
 not_working: ['-//Ximian//NONSGML Evolution Calendar//EN']
-----------------
VERSION
 working: ['2.0']
 not_working: ['2.0']
-----------------
TZID
 working: ['Europe/Berlin']
 not_working: ['Europe/Berlin']
-----------------
X-LIC-LOCATION
 working: ['Europe/Berlin']
 not_working: ['Europe/Berlin']
-----------------
TZNAME
 working: ['CEST', 'CET']
 not_working: ['CEST', 'CET']
-----------------
TZOFFSETFROM
 working: ['+0100', '+0200']
 not_working: ['+0100', '+0200']
-----------------
TZOFFSETTO
 working: ['+0100', '+0200']
 not_working: ['+0100', '+0200']
-----------------
DTSTART
 working: ['19810329T020000', '19961027T030000', '20371025T030000', '20380328T020000']
 not_working: ['19810329T020000', '19961027T030000', '20371025T030000', '20380328T020000']
-----------------
RRULE
 working: ['FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10', 'FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3', 'FREQ=YEARLY;UNTIL=20361026T010000Z;BYDAY=-1SU;BYMONTH=10', 'FREQ=YEARLY;UNTIL=20370329T010000Z;BYDAY=-1SU;BYMONTH=3']
 not_working: ['FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10', 'FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3', 'FREQ=YEARLY;UNTIL=20361026T010000Z;BYDAY=-1SU;BYMONTH=10', 'FREQ=YEARLY;UNTIL=20370329T010000Z;BYDAY=-1SU;BYMONTH=3']
-----------------
UID
 working: ['1a541f7413c5c7e4411d2d39f2572aac3dd1e4bb', '33e5e9fe887ce95f0280f8bec203d45d441cebd4', '5b81245c0d3cd1edc7096ddcd8ab26d0ac0c1075', '8fbd44192e5f670e984cc4427f59b24c0f6a2035', 'c4f274479b46d7ab001904a9f129e038a3b45838', 'd72aa72896aef1ce0a058b26a45ba4a6800a3523']
 not_working: ['3210614d-7baf-438f-a619-1bb6b0a80639', 'c1bdaf41f4ca2d29aca9566a5472e3436334a060', 'dc30e3a49a1a3b2ed3f802ae8c4aedb430bbc42b', 'dfaa6e6e8fc041a931dc73c803dc3d4323660817', 'e96d91f994370b423463e71c6a49b3d4ce742281', 'faaa9fa72fd354dea5c756fd2322694a05ce1a72']
-----------------
DTSTAMP
 working: ['20230322T151849', '20230322T151852', '20230421T070219Z', '20230508T112458Z', '20230623T063827Z', '20230630T075621Z']
 not_working: ['20230322T151841', '20230322T151846', '20230330T074717Z', '20230331T145423Z', '20230724T192133Z', '20230811T081739Z']
-----------------
SUMMARY
 working: ['Anmelden ION', 'Remove D', 'Remove D', 'Remove M', 'Remove M', 'Remove T']
 not_working: ['Abrechnung I', 'Open', 'Remove M', 'Remove N', 'Remove R', 'Remove Ro']
-----------------
DTSTART;TZID=Europe/Berlin
 working: ['20230930T100000', '20231205T100000', '20240422T100000']
 not_working: ['20230728T130000', '20230930T100000', '20231002T100000']
-----------------
DUE;TZID=Europe/Berlin
 working: ['20231003T100000', '20231208T100000', '20240424T100000']
 not_working: ['20230823T130000', '20231003T100000', '20231004T100000', '20231005T100000']
-----------------
PERCENT-COMPLETE
 working: ['0']
 not_working: ['0', '50']
-----------------
CLASS
 working: ['PUBLIC']
 not_working: ['PUBLIC']
-----------------
SEQUENCE
 working: ['1', '2']
 not_working: ['1', '2', '9']
-----------------
CREATED
 working: ['20230208T154631Z', '20230314T144337Z', '20230421T104916Z', '20230509T162658Z', '20230630T065517Z', '20230703T120334Z']
 not_working: ['20230314T144447Z', '20230320T183650Z', '20230330T120208Z', '20230403T103655Z', '20230608T063557Z', '20230730T210012Z']
-----------------
LAST-MODIFIED
 working: ['20230322T151849', '20230322T151852', '20230421T104929Z', '20230509T162658Z', '20230630T065517Z', '20230703T120353Z']
 not_working: ['20230322T151846', '20230419T145200Z', '20230419T145212Z', '20230705T074251Z', '20230731T082318Z', '20230822T075708Z']
-----------------
CATEGORIES
 working: ['ADS-B', 'Benutzerverwaltung', 'Benutzerverwaltung,EDV', 'Conference', 'EDV', 'INS', 'PhD']
 not_working: ['ADS-B', 'Benutzerverwaltung', 'Benutzerverwaltung,EDV', 'Conference', 'EDV', 'Finanzen', 'INS', 'IntegratedFieldwork', 'PhD', 'Teaching']
-----------------
DTSTART;VALUE=DATE
 working: ['20230831', '20230904', '20240201']
 not_working: ['20230605']
-----------------
DUE;VALUE=DATE
 working: ['20230901', '20231006', '20240203']
 not_working: ['20230822']
-----------------
STATUS
 working: ['NEEDS-ACTION']
 not_working: ['IN-PROCESS']
-----------------
DESCRIPTION
 working: ['Abstracts Due 01.11.2023\\n\\nhttps']
 not_working: ['- [x] Antrag gestellt\\n- [ ] Geld erhalten (58€ Hotel + Tagegeld)', 'Abstract Deadline']
-----------------
X-ALT-DESC;FMTTYPE=text/html
 working: ['<p>Abstracts Due 01.11.2023</p>\\n<p>https']
 not_working: ['<p>Abstract Deadline', '<ul>\\n<li>[x] Antrag gestellt</li>\\n<li>[ ] Geld erhalten</li>\\n</ul>\\n']
-----------------
```

EDIT:
Sorted the values in the lists.

**Comment by patrickunterwegs** [comment] 2023-08-25 22:18
Hey @q-wertz !
Thanks again for your detailed analysis!
I also went through the code again and again. I'm still not sure why this problem occurs. Still, I have made a small change that's bringing the logic closer to how it was before (before completed tasks were sorted at the end) would you mind joining the beta program on Google Play and test 2.5.4-rc?

**Comment by q-wertz** [comment] 2023-08-26 12:39
Tried version 2.05.04-rc.gplay (205040007) with the same outcome...

Also reinstalled the app (does that actually delete all config files etc?) with same results...
But after the reinstall only one is wrong (when only showing one of the two accounts)... (the one with UID `dc30e3a49a1a3b2ed3f802ae8c4aedb430bbc42b`) :sweat:
- Could it be a race condition or so? 
- I also noticed: the entry also comes after **all** the repeating tasks...

The sort/group code is in TechbeeAT/jtxBoard/app/src/main/java/at/techbee/jtx/widgets/ListWidgetContent.kt ?

Not a Java/Kotlin dev :sweat: but does it help you if I give you the 12 ics files?

**Comment by patrickunterwegs** [comment] 2023-08-26 13:09
Hey @q-wertz , 
I'm sorry that this is becoming a topic that causes so much effort...

The relevant code line is here:
https://github.com/TechbeeAT/jtxBoard/blob/develop/app/src/main/java/at/techbee/jtx/ui/list/ListViewModel.kt#L615

The actual SQL is a bit tricky, but also no rocket science:

`"$COLUMN_COMPLETED IS NOT NULL OR $COLUMN_PERCENT = 100 OR $COLUMN_DUE IS NULL, $COLUMN_DUE "`

The first part resolves in false (0) or true (1). 
It makes the first partition with all entries having no completed date, not 100 % progress OR a due date set. 
The second partition contains the rest, this should be done tasks and tasks without due date.

Each partition is then ordered by the due date. This should result in the first partition to be ordered accordingly as a due date is present.
The second partition would also be ordered by the due date showing first entries without due date (null ist sorted at the beginning of a list in SQLite) and then the remaining entries.

If you see anything suspicious, please let me know 😉

And yes, it would be great to have your entries (as long as they don't contain any sensitive or personal information) 😉 
But then I could hopefully reproduce it and debug the problem step by step.

**Comment by q-wertz** [comment] 2023-08-26 14:18
Sorry for the headaches :sweat_smile: Hope it is not just a config issue on my side...

If I find some time tomorrow I will try to dig into it a little bit.

I sent you the files per email. Content is not really private but don't want to post it public.

**Comment by patrickunterwegs** [comment] 2023-08-26 17:20
Hi @q-wertz , 
thanks again, I think with your files I found an issue (hopefully it's the only one)^^

The mistake was the comparison "progress = 100". I was thinking that the result could only be true or false, but obviously when progress is null, the result can be null, true or false - this was creating three partitions instead of two...

Well, really a stupid problem... but I hope it's fixed now =)

Could you please check again on the beta channel if it's also resolved for you? The fixed version ends with -rc3. It's still processing, but I guess it will be there within an hour.

**Comment by q-wertz** [comment] 2023-08-26 17:46
Amazing 😍

New beta is working. Perfect 😊

**Comment by patrickunterwegs** [comment] 2023-08-26 17:47
Great, thank you for the update =)
Then I can also release the current version and prepare the next =)

**Comment by patrickunterwegs** [comment] 2023-08-26 17:48
And thank you very much for your support on this! @q-wertz =)

**Closed as completed by patrickunterwegs** 2023-08-26 17:47 UTC
Labels: bug
