### ISSUE TITLE
URLs in Description not displayed

### ISSUE THREAD

**Issue by dilyanpalauzov** [TechbeeAT/jtxBoard#331] opened 2023-03-03 21:15 UTC
With jtx Board 2.02.02-rc5.ose (202020005) I load  [test.ics.txt](https://github.com/TechbeeAT/jtxBoard/files/10886144/test.ics.txt). The file contains:
```
DESCRIPTION:The event takes place from Wednesday\, 22 March until
…
 a rolling basis so hurry up and get one of the limited spots 
 available!\n\nProgram: https:
 //drive.google.com/file/d/1ew8zCpEZe_RXaysf_0uXxbAzqCLzCN8y/view?usp=shari
 ng The fee is 25€. This event is for 16 participants.
```
In dark mode after `Program: ` follows `The fee`.

The URL is not displayed

**Comment by patrickunterwegs** [comment] 2023-03-03 22:25
Thanks @dilyanpalauzov .
This issue was solved already with the update of the markdown library, I couldn't reproduce it anymore in 2.3.0. I will close this issue with the reference to the new version!

**Closed as completed** 2023-03-03 22:25 UTC
Labels: bug
